In [1]:
%matplotlib inline
%load_ext autoreload
%load_ext lab_black
%load_ext autotime
%autoreload 2

In [2]:
import copy


def show_graph(graph):
    def show_without_nan(matrix):
        display(copy.deepcopy(matrix).fillna("-"))
        return

    show_without_nan(graph.adjacency_matrix)
    for feature in graph.feature_matrix.keys():
        print(feature)
        show_without_nan(graph.feature_matrix[feature])
    return

time: 7.48 ms

# Generate wiring more easily

## Sequential

In [3]:
import graphtorch as gt
from graphtorch.wiring import connect_sequential

in_dim = 2
hidden_node_dims = [2, 4, 3]
out_dim = 3
graph = gt.Graph(in_dim, out_dim, hidden_node_dims)

graph = connect_sequential(graph)

show_graph(graph)

        I:0   H:0   H:1   H:2   O:0
FROM\TO
I:0       -  True     -     -     -
H:0       -     -  True     -     -
H:1       -     -     -  True     -
H:2       -     -     -     -  True
O:0       -     -     -     -     -

sparsity

        I:0 H:0 H:1 H:2 O:0
FROM\TO
I:0       -   1   -   -   -
H:0       -   -   1   -   -
H:1       -   -   -   1   -
H:2       -   -   -   -   1
O:0       -   -   -   -   -

wire

,I:0,H:0,H:1,H:2,O:0
FROM\TO,,,,,
I:0,-,<function default_wire at 0x7f85609da2f0>,-,-,-
H:0,-,-,<function default_wire at 0x7f85609da2f0>,-,-
H:1,-,-,-,<function default_wire at 0x7f85609da2f0>,-
H:2,-,-,-,-,<function default_wire_to_output at 0x7f85609d...
O:0,-,-,-,-,-

dimension

        I:0 H:0 H:1 H:2 O:0
FROM\TO
I:0       2   -   -   -   -
H:0       -   2   -   -   -
H:1       -   -   4   -   -
H:2       -   -   -   3   -
O:0       -   -   -   -   3

time: 984 ms

## Prarallel nodes in same layer

In [4]:
from graphtorch.wiring import connect_parallel

in_dim = 2
hidden_node_dims = [3, 4, 5, 6, 7]
out_dim = 10
graph = gt.Graph(in_dim, out_dim, hidden_node_dims)

nodes_per_hidden_layer = [2, 3]
graph = connect_parallel(graph, nodes_per_hidden_layer)

show_graph(graph)

        I:0   H:0   H:1   H:2   H:3   H:4   O:0
FROM\TO
I:0       -  True  True     -     -     -     -
H:0       -     -     -  True  True  True     -
H:1       -     -     -  True  True  True     -
H:2       -     -     -     -     -     -  True
H:3       -     -     -     -     -     -  True
H:4       -     -     -     -     -     -  True
O:0       -     -     -     -     -     -     -

sparsity

        I:0 H:0 H:1 H:2 H:3 H:4 O:0
FROM\TO
I:0       -   1   1   -   -   -   -
H:0       -   -   -   1   1   1   -
H:1       -   -   -   1   1   1   -
H:2       -   -   -   -   -   -   1
H:3       -   -   -   -   -   -   1
H:4       -   -   -   -   -   -   1
O:0       -   -   -   -   -   -   -

wire

,I:0,H:0,H:1,H:2,H:3,H:4,O:0
FROM\TO,,,,,,,
I:0,-,<function default_wire at 0x7f85609da2f0>,<function default_wire at 0x7f85609da2f0>,-,-,-,-
H:0,-,-,-,<function default_wire at 0x7f85609da2f0>,<function default_wire at 0x7f85609da2f0>,<function default_wire at 0x7f85609da2f0>,-
H:1,-,-,-,<function default_wire at 0x7f85609da2f0>,<function default_wire at 0x7f85609da2f0>,<function default_wire at 0x7f85609da2f0>,-
H:2,-,-,-,-,-,-,<function default_wire_to_output at 0x7f85609d...
H:3,-,-,-,-,-,-,<function default_wire_to_output at 0x7f85609d...
H:4,-,-,-,-,-,-,<function default_wire_to_output at 0x7f85609d...
O:0,-,-,-,-,-,-,-

dimension

        I:0 H:0 H:1 H:2 H:3 H:4 O:0
FROM\TO
I:0       2   -   -   -   -   -   -
H:0       -   3   -   -   -   -   -
H:1       -   -   4   -   -   -   -
H:2       -   -   -   5   -   -   -
H:3       -   -   -   -   6   -   -
H:4       -   -   -   -   -   7   -
O:0       -   -   -   -   -   -  10

time: 77.7 ms

## Random wiring with some parameters

In [5]:
from graphtorch.wiring import connect_randomly

in_dim = 2
hidden_node_dims = [3, 4, 5, 6, 7]
out_dim = 10
graph = gt.Graph(in_dim, out_dim, hidden_node_dims)

seed = 0
network_sparsity = 0.1
graph = connect_randomly(graph, seed, network_sparsity)

show_graph(graph)

        I:0   H:0   H:1   H:2   H:3   H:4   O:0
FROM\TO
I:0       -  True  True  True  True  True  True
H:0       -     -  True  True  True  True  True
H:1       -     -     -  True     -     -  True
H:2       -     -     -     -  True  True  True
H:3       -     -     -     -     -     -  True
H:4       -     -     -     -     -     -  True
O:0       -     -     -     -     -     -     -

sparsity

        I:0 H:0 H:1 H:2 H:3 H:4 O:0
FROM\TO
I:0       -   1   1   1   1   1   1
H:0       -   -   1   1   1   1   1
H:1       -   -   -   1   -   -   1
H:2       -   -   -   -   1   1   1
H:3       -   -   -   -   -   -   1
H:4       -   -   -   -   -   -   1
O:0       -   -   -   -   -   -   -

wire

,I:0,H:0,H:1,H:2,H:3,H:4,O:0
FROM\TO,,,,,,,
I:0,-,<function default_wire at 0x7f85609da2f0>,<function default_wire at 0x7f85609da2f0>,<function default_wire at 0x7f85609da2f0>,<function default_wire at 0x7f85609da2f0>,<function default_wire at 0x7f85609da2f0>,<function default_wire_to_output at 0x7f85609d...
H:0,-,-,<function default_wire at 0x7f85609da2f0>,<function default_wire at 0x7f85609da2f0>,<function default_wire at 0x7f85609da2f0>,<function default_wire at 0x7f85609da2f0>,<function default_wire_to_output at 0x7f85609d...
H:1,-,-,-,<function default_wire at 0x7f85609da2f0>,-,-,<function default_wire_to_output at 0x7f85609d...
H:2,-,-,-,-,<function default_wire at 0x7f85609da2f0>,<function default_wire at 0x7f85609da2f0>,<function default_wire_to_output at 0x7f85609d...
H:3,-,-,-,-,-,-,<function default_wire_to_output at 0x7f85609d...
H:4,-,-,-,-,-,-,<function default_wire_to_output at 0x7f85609d...
O:0,-,-,-,-,-,-,-

dimension

        I:0 H:0 H:1 H:2 H:3 H:4 O:0
FROM\TO
I:0       2   -   -   -   -   -   -
H:0       -   3   -   -   -   -   -
H:1       -   -   4   -   -   -   -
H:2       -   -   -   5   -   -   -
H:3       -   -   -   -   6   -   -
H:4       -   -   -   -   -   7   -
O:0       -   -   -   -   -   -  10

time: 141 ms